# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
     runs-on: windows-latest
      steps:
      - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Run PMD analysis
      run: |
        Invoke-WebRequest -Uri "https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.39.0/pmd-bin-6.39.0.zip" -OutFile "pmd-bin-6.39.0.zip"
        Expand-Archive -Path "pmd-bin-6.39.0.zip" -DestinationPath "."
        .\pmd-bin-6.39.0\bin\pmd.bat -d ./src -R rulesets/apex/quickstart.xml -f text

    - name: Check code quality
      id: code-quality
      run: |
        npm run lint
        $quality = (npm run quality-check)  # Assuming quality-check script returns a percentage
        echo "QUALITY=$quality" >> $env:GITHUB_ENV

    - name: Create pull request
      if: github.ref == 'refs/heads/SIT'
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: SIT
        base: main
        title: 'SIT to main PR'
        body: 'Auto-generated PR from SIT branch'

    - name: Deploy if quality is above 75%
      if: env.QUALITY > 75
      run: echo "Code quality is above 75%, proceeding with deployment..."

    - name: Setup Salesforce CLI
      uses: forcedotcom/cli-action@v1
   
